### PR TITLE
Fix: as of lttng-modules 2.6, we need an additionnal header

### PR DESCRIPTION
**Pull request by jdesfossez**
Signed-off-by: Julien Desfossez <jdesfossez@efficios.com>

### CODE REVIEW

**Comment by jgalar** [comment]
Was this ever merged?

**Comment by eepp** [comment]
Nope! I was planning to wait a full year when I wrote "shortly", so this should be merged in 8 days.

**Comment by jgalar** [comment]
That's what I figured. :neckbeard:

**Comment by eepp** [comment]
I reviewed this thoroughly during the last year and decided to accept it.

Merged (41aea25854c60e346ab5f46ae5b2575e19d7a850), thanks.

**Pull request closed without merging**
